
import abudabi1 from "../assets/images/abudabi1.jfif"
import abudabi2 from "../assets/images/abudabi2.jfif"
import abudabi3 from "../assets/images/abudabi3.jfif"
import abudabi4 from "../assets/images/abudabi4.jfif"
import Shrjah from "../assets/images/Shrjah.jpg"
import Fujehra from "../assets/images/Fujehra3.jpg"

export const cityTourArray=[
    {
    name:"Dubai City Tour",
    desription:"Discover Dubai’s historical, cultural, and unequaled modern side all on this comprehensive Dubai city tour! With roundtrip hotel transfers, this allows you to take in the region’s mix of old, iconic, and celebrated landmarks.The four-hour Dubai city tour package by desert safari tours is one of the best ways to explore the both historic and glittering side of Dubai that is often referred to as the Middle East’s gem. The tour includes a visit to Dubai Museum that is housed within the 18th century Al Fahidi Fort. It has on display arts and artifacts reflecting the ancient history and lifestyle of traditional Arabs. An ideal illustration of a blend of outstanding Islamic and contemporary architecture, Jumeirah Mosque is another popular point of interest covered in the itinerary.",
    ofers1:"⦁	Photo stop at Dubai Creek",
    ofers2:"	Dubai Museum",
    ofers3:" Drive through Jumeira Road",
    ofers4:" Visit at Jumeirah Mosque",
    ofers5:" Photo stop at Burj Al Arab Outside Only",
    ofers6:" 	Tour of Palm Jumeria and Atlantis photo stop",
    ofers7:" 	Bottled water",
    desr2:"For a peep into the glitzy side of Dubai, our itinerary further comprises a tour to such phenomenal attractions of the city as Burj Al Arab Hotel – the world’s only seven-star hotel that is especially noted for its distinctive silhouette resembling a billowing sail, the Palm Island – the crescent shaped man-made island, Atlantis Hotel and Burj Khalifa – the towering building that is one of its kind in the whole world. Equally noteworthy is Dubai’s scenic attractions, and a photo stop to well-maintained Jumeirah Beach will provide you with a unique opportunity to immerse in the city’s natural beauty.s",
    SAFETY:"SAFETY:",
    SAFETYData:"Our drivers are professional and licensed drivers and are trained in first aid. Our cars are fitted with roll cage to protect the occupants from being injured in an accident, particularly in the event of a roll-over in the desert which is very rare. Plus there are seat belts for every passenger. We use 4x4 Land Cruisers for our safari. Also from the moment you are in our cars you are insured. All our cars and the passengers are covered under insurance.",
    MUSTDO:"MUST DO'S:",
    MUSTDOData:"One must get a camera when going to a desert safari in Dubai as the views are breath-taking and awesome. Also one should wear comfortable clothes and avoid jewelry or expensive watch and cell phones as there is no signal at the camps. Do try the Arabic coffee at the camp and shake your belly with our belly dancer!",
    price:"159",
    image:abudabi1,
    timeAndDate:"1PM - 3PM, 20th Apr (3 Hours)",
    totalGuest:"10AM To 8PM"
},
{
    name:"Abu Dhabi City Tour",
    desription:"Get to know the UAE’s capital city and its fantastic historical, cultural, and thrilling sights with our Abu Dhabi city tour. With transfers arranged to and from Dubai, it allows you to discover Abu Dhabi’s diverse shades and persona. On an Abu Dhabi city tour with us, know how the capital city of the United Arab Emirates incredibly merges its rich ancient heritage with the most modern contemporary life. We’ve crafted this tour package with cautiously picked highlights of Abu Dhabi to ensure that you don’t miss out to take in its significant sights. So be prepared to behold some of the most majestic landmarks of the UAE, as we pick you up from your hotel or preferred location in Dubai for a two-hour drive to Abu Dhabi. ",
    ofers1:"Pick up from your hotel  ",
    ofers2:" Ferrari World (Stopover)",
    ofers3:" Date market (Stopover)",
    ofers4:" Drive through Corniche with a Photo stop",
    ofers5:"Emirates Palace Hotel (Photo stop)",
    ofers6:"Sheikh Zayed Mosque",
    ofers7:"Drop off at your hotel",
    desr2:"Before we head out to Abu Dhabi’s most modern attractions including Ferrari World and Yas Island, we’ll take you to Heritage Village that serves as a window to the region’s past. Eventually, the trip culminates with a visit to Abu Dhabi WTC Mall, where you’ll come across a whole lot of retail outlets selling unique, name-brand and luxury items. Upon a full-day, unforgettable trip, we would drop you back to your rendezvous spot in Dubai.",
    SAFETY:"SAFETY",
    SAFETYData:"Our drivers are professional and licensed drivers and are trained in first aid. Our cars are fitted with roll cage to protect the occupants from being injured in an accident, particularly in the event of a roll-over in the desert which is very rare. Plus there are seat belts for every passenger. We use 4x4 Land Cruisers for our safari. Also from the moment you are in our cars you are insured. All our cars and the passengers are covered under insurance.",
    MUSTDO:"MUST DO'S",
    MUSTDOData:"One must get a camera when going to a desert safari in Dubai as the views are breath-taking and awesome. Also one should wear comfortable clothes and avoid jewelry or expensive watch and cell phones as there is no signal at the camps. Do try the Arabic coffee at the camp and shake your belly with our belly dancer!",
    price:"49",
    image:abudabi2,
    timeAndDate:"12PM - 3PM, 20th Apr (3 Hours)",
    totalGuest:"9AM To 4PM"
},
{
    name:"Ajman City Tour",
    desription:"DESERT SAFARI DUBAI suggest you take a detailed tour to Ajman and experience the hidden beauty of this emirate before concluding your tour to UAE. Expanded over 148 KM2 area, this (comparatively) small part of UAE has much to contribute to the century old history of Arabs. For offering you a comprehensive Ajman tour, we’ve created different packages for easy selection.When you want to cherish every moment of your holidays, we fulfill your wish by offering a personalized itinerary during the Ajman stop. We create a strategic travelling plan to take you on a fun and amusing journey in Ajman and show you around the place like you never expected before. We include every monumental sight in our Ajman tour including Al Murabbaa Watchtower, Ajman Shaikh Zayed Mosque and Aqua Bounce Ajman. For offering you a refreshment time after a long journey around the city, we include a picnic spot at Wasit Wetland Centre and Wasit Nature Reserve.",
    ofers1:"Fuel surcharge",
    ofers2:" Local taxes",
    ofers3:" National Park fees",
    ofers4:" Bottled water",
    ofers5:" Driver/guide",
    ofers6:" Hotel/port pickup and drop-off",
    ofers7:" Private tour",
    desr2:"We never want you to miss the chance to understand the cultural and political value of Ajman city, so we include Ajman Museum in your tour, too. This way you can get to know the long history of this part of UAE that has remained important throughout the formation of United Arab Emirates. For making your trip exciting, we arrange half city tour for sightseeing where you can make vlogs, take pictures, and carry all the beautiful memories of your Ajman city back with you. Select a package and continue your fun ride with DESERT SAFARI DUBAI.",
    SAFETY:"SAFETY",
    SAFETYData:"Our drivers are professional and licensed drivers and are trained in first aid. Our cars are fitted with roll cage to protect the occupants from being injured in an accident, particularly in the event of a roll-over in the desert which is very rare. Plus there are seat belts for every passenger. We use 4x4 Land Cruisers for our safari. Also from the moment you are in our cars you are insured. All our cars and the passengers are covered under insurance.",
    MUSTDO:"MUST DO'S",
    MUSTDOData:"One must get a camera when going to a desert safari in Dubai as the views are breath-taking and awesome. Also one should wear comfortable clothes and avoid jewelry or expensive watch and cell phones as there is no signal at the camps. Do try the Arabic coffee at the camp and shake your belly with our belly dancer!",
    price:"159",
    image:abudabi3,
    timeAndDate:"3PM - 3PM, 20th Apr (3 Hours)",
    totalGuest:"05 Hours Approx"
},
{
    name:"Sharjah City Tour",
    desription:"Have a big family celebration coming up? Parties and festive events are an excellent time to relax and focus on things that matter most, our family. While any day playing with your little ones or going for a date night with your partner might be fun, you are losing out on all other exciting activities you can enjoy. Plan a proper holiday to Sharjah, spend a good few day away from work and tick it off your bucket list!",
    ofers1:"Explore the Desert",
    ofers2:"Sun, Sand & Swimming!",
    ofers3:"Nightlife Merriment",
    ofers4:" Souvenir Shopping!",
    ofers5:" Enjoy the History",
    ofers6:" Old Car Museum",
    ofers7:" Fire show and Tanura show",
    desr2:"Sharjah is a historic destination and is a city where you will be hard-pressed to choose which museum to head to first. From the Science Museum to the Archaeology Museum & the Heritage Museum.We love to shop! And after staying indoors and shopping online, there is new energy when you head over to a mall or a local boutique.",
    SAFETY:"SAFETY",
    SAFETYData:"Our drivers are professional and licensed drivers and are trained in first aid. Our cars are fitted with roll cage to protect the occupants from being injured in an accident, particularly in the event of a roll-over in the desert which is very rare. Plus there are seat belts for every passenger. We use 4x4 Land Cruisers for our safari. Also from the moment you are in our cars you are insured. All our cars and the passengers are covered under insurance.",
    MUSTDO:"MUST DO'S",
    MUSTDOData:"One must get a camera when going to a desert safari in Dubai as the views are breath-taking and awesome. Also one should wear comfortable clothes and avoid jewelry or expensive watch and cell phones as there is no signal at the camps. Do try the Arabic coffee at the camp and shake your belly with our belly dancer!",
    price:"159",
    image:Shrjah,
    timeAndDate:"9PM - 3PM, 20th Apr (1 Hours)",
    totalGuest:"05 Hours Approx"
},
{
    name:"Fujehra City Tour",
    desription:"Overview Fujairah lies on the UAE east coast, about two hours’ drive from Dubai. With this full-day tour, experience the sights and slower tempo of this traditional emirate without cab or car rental hassles, and with a guide for history. Pass mountains, ‘wadi’ gorges, and beaches by air-conditioned coach; and visit Fujairah Fort, a 15th-century mosque, Fujairah Museum, and a market, with ease. Entry fees and return Dubai hotel transfers included. Discover a slower UAE on a full-day tour to east-coast Fujairah from Dubai See Fujairah’s highlights with ease by coach, with a guide for insight Visit Fujairah Museum, browse the Friday Market, see Fujairah Fort, and more Useful touches: entry fees and Dubai hotel pickup and drop-off included",
    ofers1:"Bottled water",
    ofers2:" Driver/guide",
    ofers3:"Professional photographer guide",
    ofers4:" Sun Set Photography",
    ofers5:" Hotel pickup and drop-off",
    ofers6:" Souvenir photos (available to purchase)",
    ofers7:" Food and drinks",
    desr2:"There is no minimum people required for this package, even 1 person can do this. The best is if you have a group of 6 people in which you get a complete car for your group and don't have to share it with other guests. Please note as the desert safari is an adventure activity we do not recommend children below 3 years, pregnant women and older adults especially with back problems. But we can arrange private car that can take you directly to the camp so that you may enjoy other activities in the camp. We also have car seats for children.",
    SAFETY:"SAFETY",
    SAFETYData:"Our drivers are professional and licensed drivers and are trained in first aid. Our cars are fitted with roll cage to protect the occupants from being injured in an accident, particularly in the event of a roll-over in the desert which is very rare. Plus there are seat belts for every passenger. We use 4x4 Land Cruisers for our safari. Also from the moment you are in our cars you are insured. All our cars and the passengers are covered under insurance.",
    MUSTDO:"MUST DO'S",
    MUSTDOData:"One must get a camera when going to a desert safari in Dubai as the views are breath-taking and awesome. Also one should wear comfortable clothes and avoid jewelry or expensive watch and cell phones as there is no signal at the camps. Do try the Arabic coffee at the camp and shake your belly with our belly dancer!",
    // SANDSKI:"SAND SKI",
    // SANDSKIData:"A very popular part of the desert safari. You get to ski from the highest dunes on a ski board, everyone can do it, as if you fall the soft sand is there to catch you. A thrilling experience and one that everyone should do a desert safari. We recommend you to book the red dune safari to enjoy sand-skiing the best.",
    // CAMELTREK:"CAMEL TREK",
    // CAMELTREKData:"Another popular activity in the desert is the camel trek. Enjoy the sunset while you are on the highest dune going towards the camp where you have drinks and dinner waiting for you.",
    price:"159",
    image:Fujehra,
    timeAndDate:"12PM - 3PM, 20th Apr (3 Hours)",
    totalGuest:"05 Hours Approx"
}, 
]
