
import cardImage from "../assets/images/cardImg2.jpg"
import cardImage2 from "../assets/images/cardImg.jpg"
import cardImage3 from "../assets/images/cardImg3.jpg"
import cardImage4 from "../assets/images/ticketimage.jpg"
export const desertSefariArray=[
    {
    name:"Morning Desert Sefari",
    desription:"Well, Dubai adds lots of adventures and thrill to your trip. And if you are one of the visitors who really want to turn up your day, let’s repeat it with me Morning desert safari is an obvious go. Where desert symbolizes a barren sandy piece of land with no life there, contrary to this, it’s not the case with deserts here in UAE.And to say that this desert safari should be a “Must have” adventure in your trip list. And more specifically, morning in the desert allows you to start your day with the ultimate fun-packed experience and joy.The story of the morning desert safari is very simple here. When the sun is about to shine at the emirate’s land, it’s time to prepare yourself for a whole new morning experience. Your desert journey to absolute jollity rightly starts where a 4×4 Land cruiser picks you from the hotel at 9 AM (usually time varies with your package). Let’s embrace yourself to see a new face of deserts with a morning safari",
   ofers1:"Pick up by 4x4 wheel Drive from any point in Dubai between 3.00 PM to 3.30 PM – timings are subject to change as per sunset time",
   ofers2:" Drive through the desert along Al Awir Road - Dune Bashing",
   ofers3:" 20-30 minutes Dune Driving",
   ofers4:" Sun Set Photography",
   ofers5:" Camel Rides",
   ofers6:" Belly Dancing (not during Ramadan)",
   ofers7:" Fire show and Tanura show",
   desr2:"There is no minimum people required for this package, even 1 person can do this. The best is if you have a group of 6 people in which you get a complete car for your group and don't have to share it with other guests. Please note as the desert safari is an adventure activity we do not recommend children below 3 years, pregnant women and older adults especially with back problems. But we can arrange private car that can take you directly to the camp so that you may enjoy other activities in the camp. We also have car seats for children.",
   SAFETY:"SAFETY",
   SAFETYData:"Our drivers are professional and licensed drivers and are trained in first aid. Our cars are fitted with roll cage to protect the occupants from being injured in an accident, particularly in the event of a roll-over in the desert which is very rare. Plus there are seat belts for every passenger. We use 4x4 Land Cruisers for our safari. Also from the moment you are in our cars you are insured. All our cars and the passengers are covered under insurance.",
   MUSTDO:"MUST DO'S",
   MUSTDOData:"One must get a camera when going to a desert safari in Dubai as the views are breath-taking and awesome. Also one should wear comfortable clothes and avoid jewelry or expensive watch and cell phones as there is no signal at the camps. Do try the Arabic coffee at the camp and shake your belly with our belly dancer!",
   SANDSKI:"SAND SKI",
   SANDSKIData:"A very popular part of the desert safari. You get to ski from the highest dunes on a ski board, everyone can do it, as if you fall the soft sand is there to catch you. A thrilling experience and one that everyone should do a desert safari. We recommend you to book the red dune safari to enjoy sand-skiing the best.",
//    CAMELTREK:"CAMEL TREK",
//    CAMELTREKData:"Another popular activity in the desert is the camel trek. Enjoy the sunset while you are on the highest dune going towards the camp where you have drinks and dinner waiting for you.",
   price:"199",
    image:cardImage,
    timeAndDate:"8AM To 9AM (2 Hours)",
    deserName:"Morning desert sefari",
    totalGuest:"06"
},
{
    name:"Evening Desert Safari",
    desription:"Evening Desert Safari Dubai is a 6 Hour Tour in the Desert full of Excitement and Thrill. The voyage combines various activities like Dune Bashing, Belly Dancing, Tanura Dance, Camel Riding, Sand Boarding and Horse Riding. Not only is this, but your palate is also taken care of; delicious BBQ Dinner with Veg and non-Veg Optional Dishes are served during your Evening Desert Safari Tour.A interesting travel experience in Dubai’s desert is just one click away, and there are a plethora of things to choose from. From camel riding to belly dancing to photographing breathtaking sunsets, Dubai Desert Safari is a comprehensive package for anyone looking to be thoroughly amused.",
    //ofers1:"Pick up by 4x4 wheel Drive from any point in Dubai between 3.00 PM to 3.30 PM – timings are subject to change as per sunset time",
    ofers2:" Drive through the desert along Al Awir Road - Dune Bashing",
    ofers3:" 20-30 minutes Dune Driving",
    ofers4:" Sun Set Photography",
    ofers5:" Camel Rides",
    ofers6:" Belly Dancing (not during Ramadan)",
    ofers7:" Fire show and Tanura show",
    desr2:"There is no minimum people required for this package, even 1 person can do this. The best is if you have a group of 6 people in which you get a complete car for your group and don't have to share it with other guests. Please note as the desert safari is an adventure activity we do not recommend children below 3 years, pregnant women and older adults especially with back problems. But we can arrange private car that can take you directly to the camp so that you may enjoy other activities in the camp. We also have car seats for children.",
    SAFETY:"SAFETY",
    SAFETYData:"Our drivers are professional and licensed drivers and are trained in first aid. Our cars are fitted with roll cage to protect the occupants from being injured in an accident, particularly in the event of a roll-over in the desert which is very rare. Plus there are seat belts for every passenger. We use 4x4 Land Cruisers for our safari. Also from the moment you are in our cars you are insured. All our cars and the passengers are covered under insurance.",
    MUSTDO:"MUST DO'S",
    MUSTDOData:"One must get a camera when going to a desert safari in Dubai as the views are breath-taking and awesome. Also one should wear comfortable clothes and avoid jewelry or expensive watch and cell phones as there is no signal at the camps. Do try the Arabic coffee at the camp and shake your belly with our belly dancer!",
    SANDSKI:"SAND SKI",
    SANDSKIData:"A very popular part of the desert safari. You get to ski from the highest dunes on a ski board, everyone can do it, as if you fall the soft sand is there to catch you. A thrilling experience and one that everyone should do a desert safari. We recommend you to book the red dune safari to enjoy sand-skiing the best.",
    CAMELTREK:"CAMEL TREK",
    CAMELTREKData:"Another popular activity in the desert is the camel trek. Enjoy the sunset while you are on the highest dune going towards the camp where you have drinks and dinner waiting for you.",
    price:"199",
    image:cardImage2,
    timeAndDate:"2PM - 9PM (6 Hours)",
    deserName:"Evening desert sefari",
    totalGuest:"06"
},
{
    name:"Dune Buggy Ride",
    desription:"This tour starts in the afternoon across the desert of Dubai with several stops for photography. During an exciting dune drive you arrive at the first destination for a beautiful sunset. We stop to watch the sunset and continue with Dune bashing to finally reach our campsite. Here you have the opportunity to do a camel ride, sand boarding and try out a henna design on hand or feet. After working up an appetite you get to enjoy a delicious barbecue dinner and shisha (the famous Arabic water pipe). You also get to enjoy our Fire show and Tanura show performance around the campfire by starlight.",
    //ofers1:"Pick up by 4x4 wheel Drive from any point in Dubai between 3.00 PM to 3.30 PM – timings are subject to change as per sunset time",
    ofers2:" Drive through the desert along Al Awir Road - Dune Bashing",
    ofers3:" 20-30 minutes Dune Driving",
    ofers4:" Sun Set Photography",
    ofers5:" Camel Rides",
    ofers6:" Belly Dancing (not during Ramadan)",
    ofers7:" Fire show and Tanura show",
    desr2:"There is no minimum people required for this package, even 1 person can do this. The best is if you have a group of 6 people in which you get a complete car for your group and don't have to share it with other guests. Please note as the desert safari is an adventure activity we do not recommend children below 3 years, pregnant women and older adults especially with back problems. But we can arrange private car that can take you directly to the camp so that you may enjoy other activities in the camp. We also have car seats for children.",
    SAFETY:"SAFETY",
    SAFETYData:"Our drivers are professional and licensed drivers and are trained in first aid. Our cars are fitted with roll cage to protect the occupants from being injured in an accident, particularly in the event of a roll-over in the desert which is very rare. Plus there are seat belts for every passenger. We use 4x4 Land Cruisers for our safari. Also from the moment you are in our cars you are insured. All our cars and the passengers are covered under insurance.",
    MUSTDO:"MUST DO'S",
    MUSTDOData:"One must get a camera when going to a desert safari in Dubai as the views are breath-taking and awesome. Also one should wear comfortable clothes and avoid jewelry or expensive watch and cell phones as there is no signal at the camps. Do try the Arabic coffee at the camp and shake your belly with our belly dancer!",
    SANDSKI:"SAND SKI",
    SANDSKIData:"A very popular part of the desert safari. You get to ski from the highest dunes on a ski board, everyone can do it, as if you fall the soft sand is there to catch you. A thrilling experience and one that everyone should do a desert safari. We recommend you to book the red dune safari to enjoy sand-skiing the best.",
   
    price:"299",
    image:cardImage3,
    timeAndDate:"Approx 1 Hours",
    deserName:"Overnight Sefari",
    totalGuest:"06"
},
{
    name:"Quad Bike Sefari",
    desription:"This tour starts in the afternoon across the desert of Dubai with several stops for photography. During an exciting dune drive you arrive at the first destination for a beautiful sunset. We stop to watch the sunset and continue with Dune bashing to finally reach our campsite. Here you have the opportunity to do a camel ride, sand boarding and try out a henna design on hand or feet. After working up an appetite you get to enjoy a delicious barbecue dinner and shisha (the famous Arabic water pipe). You also get to enjoy our Fire show and Tanura show performance around the campfire by starlight.",
    //ofers1:"Pick up by 4x4 wheel Drive from any point in Dubai between 3.00 PM to 3.30 PM – timings are subject to change as per sunset time",
    ofers2:" Drive through the desert along Al Awir Road - Dune Bashing",
    ofers3:" 20-30 minutes Dune Driving",
    ofers4:" Sun Set Photography",
    ofers5:" Camel Rides",
    ofers6:" Belly Dancing (not during Ramadan)",
    ofers7:" Fire show and Tanura show",
    desr2:"There is no minimum people required for this package, even 1 person can do this. The best is if you have a group of 6 people in which you get a complete car for your group and don't have to share it with other guests. Please note as the desert safari is an adventure activity we do not recommend children below 3 years, pregnant women and older adults especially with back problems. But we can arrange private car that can take you directly to the camp so that you may enjoy other activities in the camp. We also have car seats for children.",
    SAFETY:"SAFETY",
    SAFETYData:"Our drivers are professional and licensed drivers and are trained in first aid. Our cars are fitted with roll cage to protect the occupants from being injured in an accident, particularly in the event of a roll-over in the desert which is very rare. Plus there are seat belts for every passenger. We use 4x4 Land Cruisers for our safari. Also from the moment you are in our cars you are insured. All our cars and the passengers are covered under insurance.",
    MUSTDO:"MUST DO'S",
    MUSTDOData:"One must get a camera when going to a desert safari in Dubai as the views are breath-taking and awesome. Also one should wear comfortable clothes and avoid jewelry or expensive watch and cell phones as there is no signal at the camps. Do try the Arabic coffee at the camp and shake your belly with our belly dancer!",
    SANDSKI:"SAND SKI",
    SANDSKIData:"A very popular part of the desert safari. You get to ski from the highest dunes on a ski board, everyone can do it, as if you fall the soft sand is there to catch you. A thrilling experience and one that everyone should do a desert safari. We recommend you to book the red dune safari to enjoy sand-skiing the best.",
   
    price:"399",
    image:cardImage4,
    timeAndDate:"Approx 30 Minutes",
    deserName:"Dune Buggy Ride",
    totalGuest:"02"
},

{
    name:"Quad Bike Ride",
    desription:"This tour starts in the afternoon across the desert of Dubai with several stops for photography. During an exciting dune drive you arrive at the first destination for a beautiful sunset. We stop to watch the sunset and continue with Dune bashing to finally reach our campsite. Here you have the opportunity to do a camel ride, sand boarding and try out a henna design on hand or feet. After working up an appetite you get to enjoy a delicious barbecue dinner and shisha (the famous Arabic water pipe). You also get to enjoy our Fire show and Tanura show performance around the campfire by starlight.",
    //ofers1:"Pick up by 4x4 wheel Drive from any point in Dubai between 3.00 PM to 3.30 PM – timings are subject to change as per sunset time",
    ofers2:" Drive through the desert along Al Awir Road - Dune Bashing",
    ofers3:" 20-30 minutes Dune Driving",
    ofers4:" Sun Set Photography",
    ofers5:" Camel Rides",
    ofers6:" Belly Dancing (not during Ramadan)",
    ofers7:" Fire show and Tanura show",
    desr2:"There is no minimum people required for this package, even 1 person can do this. The best is if you have a group of 6 people in which you get a complete car for your group and don't have to share it with other guests. Please note as the desert safari is an adventure activity we do not recommend children below 3 years, pregnant women and older adults especially with back problems. But we can arrange private car that can take you directly to the camp so that you may enjoy other activities in the camp. We also have car seats for children.",
    SAFETY:"SAFETY",
    SAFETYData:"Our drivers are professional and licensed drivers and are trained in first aid. Our cars are fitted with roll cage to protect the occupants from being injured in an accident, particularly in the event of a roll-over in the desert which is very rare. Plus there are seat belts for every passenger. We use 4x4 Land Cruisers for our safari. Also from the moment you are in our cars you are insured. All our cars and the passengers are covered under insurance.",
    MUSTDO:"MUST DO'S",
    MUSTDOData:"One must get a camera when going to a desert safari in Dubai as the views are breath-taking and awesome. Also one should wear comfortable clothes and avoid jewelry or expensive watch and cell phones as there is no signal at the camps. Do try the Arabic coffee at the camp and shake your belly with our belly dancer!",
    SANDSKI:"SAND SKI",
    SANDSKIData:"A very popular part of the desert safari. You get to ski from the highest dunes on a ski board, everyone can do it, as if you fall the soft sand is there to catch you. A thrilling experience and one that everyone should do a desert safari. We recommend you to book the red dune safari to enjoy sand-skiing the best.",
   
    price:"551",
    image:cardImage,
    timeAndDate:"9PM - 3PM, 20th Apr (1 Hours)",
    totalGuest:"02"
},
{
    name:"Camel Ride",
    desription:"This tour starts in the afternoon across the desert of Dubai with several stops for photography. During an exciting dune drive you arrive at the first destination for a beautiful sunset. We stop to watch the sunset and continue with Dune bashing to finally reach our campsite. Here you have the opportunity to do a camel ride, sand boarding and try out a henna design on hand or feet. After working up an appetite you get to enjoy a delicious barbecue dinner and shisha (the famous Arabic water pipe). You also get to enjoy our Fire show and Tanura show performance around the campfire by starlight.",
    //ofers1:"Pick up by 4x4 wheel Drive from any point in Dubai between 3.00 PM to 3.30 PM – timings are subject to change as per sunset time",
    ofers2:" Drive through the desert along Al Awir Road - Dune Bashing",
    ofers3:" 20-30 minutes Dune Driving",
    ofers4:" Sun Set Photography",
    ofers5:" Camel Rides",
    ofers6:" Belly Dancing (not during Ramadan)",
    ofers7:" Fire show and Tanura show",
    desr2:"There is no minimum people required for this package, even 1 person can do this. The best is if you have a group of 6 people in which you get a complete car for your group and don't have to share it with other guests. Please note as the desert safari is an adventure activity we do not recommend children below 3 years, pregnant women and older adults especially with back problems. But we can arrange private car that can take you directly to the camp so that you may enjoy other activities in the camp. We also have car seats for children.",
    SAFETY:"SAFETY",
    SAFETYData:"Our drivers are professional and licensed drivers and are trained in first aid. Our cars are fitted with roll cage to protect the occupants from being injured in an accident, particularly in the event of a roll-over in the desert which is very rare. Plus there are seat belts for every passenger. We use 4x4 Land Cruisers for our safari. Also from the moment you are in our cars you are insured. All our cars and the passengers are covered under insurance.",
    MUSTDO:"MUST DO'S",
    MUSTDOData:"One must get a camera when going to a desert safari in Dubai as the views are breath-taking and awesome. Also one should wear comfortable clothes and avoid jewelry or expensive watch and cell phones as there is no signal at the camps. Do try the Arabic coffee at the camp and shake your belly with our belly dancer!",
    SANDSKI:"SAND SKI",
    SANDSKIData:"A very popular part of the desert safari. You get to ski from the highest dunes on a ski board, everyone can do it, as if you fall the soft sand is there to catch you. A thrilling experience and one that everyone should do a desert safari. We recommend you to book the red dune safari to enjoy sand-skiing the best.",
   
    price:"51",
    image:cardImage,
    timeAndDate:"12PM - 3PM, 20th Apr (3 Hours)",
    totalGuest:"10"
},   
 {
    name:"Overnight Sefari",
    desription:"Overnight Desert Safari offers various drills to relish in the desert and it’s best for you. Undergo the fervor filled for the time being Dubai Overnight to broaden your legacy ordeal of the Middle East. We offer our visitors the stunning Overnight Safari in Desert visit to give you a dramatic look at the desert way of life and culture of the Middle East.Our total affair visit, the Dubai Overnight Desert Safari enlarges your Dubai legacy experience with a startling Overnight visit under the moon and starlit sky at our campsite. We offer you a chance to make a stride back on the Overnight Safari Desert record and suffer how Dubai was around fifty years back.",
    ofers1:" Dune Bashing",
    ofers2:" Dune Bashing in 4x4",
    ofers3:"Buffet Dinner, and BBQ",
    ofers4:" Arabic Coffee (gahwa) and fresh dates welcome at camp",
    ofers5:"Tents Stay in The Desert Of Dubai",
    ofers6:"Air-conditioned vehicle",
    ofers7:"Live Entertainment Performance",
    MUSTDO:"MUST DO'S",
    SANDSKIData:"Do get a tripod if you have a camera, which you can use, as the night sky and the morning sun rise in the desert is really beautiful. Carry your towels and basic toiletries, we advise not to carry a big bag as our cars really don't have space for any luggage. If you are spending your first night at the camp when you are in Dubai, please check in your luggage at the hotel where you are going to stay next. Leave all the electronics at home/hotel as there are no electrical points at the camp and the whole experience of the desert is to enjoy the sounds of the desert and the night.",
    SANDSKI:"SAND SKI",
    MUSTDOData:"A very popular part of the desert safari. You get to ski from the highest dunes on a ski board, everyone can do it, as if you fall the soft sand is there to catch you. A thrilling experience and one that everyone should do a desert safari. We recommend you to book the red dune safari to enjoy sand-skiing the best.",
    CAMELTREK:"CAMEL TREK",
    CAMELTREKData:"Another popular activity in the desert is the camel trek. Enjoy the sunset while you are on the highest dune going towards the camp where you have drinks and dinner waiting for you.",
    price:"551",
    image:cardImage,
    timeAndDate:"12PM - 3PM, 3th Apr (3 Hours)",
    totalGuest:"10"
},    {
    name:"Dinner in Desert",
    desription:"A minimum of 2 people would make this safari exceptionally enjoyable but, if you are alone, do not hesitate to book this overnight desert safari Dubai. The overnight Dubai safari is an extension of the evening desert safari and commences once the guests of the evening safari have left the campsite. You can relax at the overnight tent during the night and enjoy the starry desert experience. Tent along with mattresses, pillows and blankets will be provided. We do have washroom and shower facilities at the desert safari camp. You will be served fresh breakfast in the morning along with tea/coffee before you head back to your hotel.",
    ofers1:" Pick up from all centrally located hotels in Dubai and meeting point in Sharjah",
    ofers2:" Dune Bashing in 4x4",
    ofers3:"Sunset photography stop",
    ofers4:" Arabic Coffee (gahwa) and fresh dates welcome at camp",
    ofers5:" Camel rides",
    ofers6:"Belly dance show (not during Ramadan)",
    ofers7:"Bar - On Payment basis - (not during Ramadan)",
    MUSTDO:"MUST DO'S",
    SANDSKIData:"Do get a tripod if you have a camera, which you can use, as the night sky and the morning sun rise in the desert is really beautiful. Carry your towels and basic toiletries, we advise not to carry a big bag as our cars really don't have space for any luggage. If you are spending your first night at the camp when you are in Dubai, please check in your luggage at the hotel where you are going to stay next. Leave all the electronics at home/hotel as there are no electrical points at the camp and the whole experience of the desert is to enjoy the sounds of the desert and the night.",
    SANDSKI:"SAND SKI",
    MUSTDOData:"A very popular part of the desert safari. You get to ski from the highest dunes on a ski board, everyone can do it, as if you fall the soft sand is there to catch you. A thrilling experience and one that everyone should do a desert safari. We recommend you to book the red dune safari to enjoy sand-skiing the best.",
    
    SAFETY:"SAFETY",
    SAFETYData:"Our drivers are professional and licensed drivers and are trained in first aid. Our cars are fitted with roll cage to protect the occupants from being injured in an accident, particularly in the event of a roll-over in the desert which is very rare. Plus there are seat belts for every passenger. We use 4x4 Land Cruisers for our safari. Also from the moment you are in our cars you are insured. All our cars and the passengers are covered under insurance.",
    price:"251",
    image:cardImage,
    timeAndDate:"12PM - 3PM, 20th Apr (5 Hours)",
    totalGuest:"7"
},

]
