
import dhow1 from "../assets/images/dhow1.jfif"
import dhow2 from "../assets/images/dhow2.jfif"
import dhow3 from "../assets/images/dhow3.jfif"
import dhow4 from "../assets/images/dhow4.jfif"


export const DhowCruiseArray=[
    {
    name:"Dhow Creek Cruise",
    desription:"Dubai is more beautiful and attractive in the evening and in the night. Dhow Creek Cruise is an outstanding experience of spending the holiday and to make it gracious. Basically, it is also another way of sightseeing and viewing the wonders of city with your friends and family. In the evening under the moonlight and by seeing the other bright things of city will make you happy because it seems to be the part of heaven in the world",
    ofers1:"Pick up by 4x4 wheel Drive from any point in Dubai between 3.00 PM to 3.30 PM – timings are subject to change as per sunset time",
    ofers2:"Romantic ambiance at our Dhow while cruising & dining aboard",
    ofers3:"Welcome non-alcoholic drink on arrival",
    ofers4:" Two hours cruising on Dubai Creek",
    ofers5:"Fully Air-conditioned lower deck and open-air upper deck",
    ofers6:" Sumptuous Continental & Asian buffet dinner",
    ofers7:"Unlimited soft drinks, mineral water, tea, and coffee",
    desr2:"There is no minimum people required for this package, even 1 person can do this. The best is if you have a group of 6 people in which you get a complete car for your group and don't have to share it with other guests. Please note as the desert safari is an adventure activity we do not recommend children below 3 years, pregnant women and older adults especially with back problems. But we can arrange private car that can take you directly to the camp so that you may enjoy other activities in the camp. We also have car seats for children.",
    SAFETY:"SAFETY",
    SAFETYData:"Our drivers are professional and licensed drivers and are trained in first aid. Our cars are fitted with roll cage to protect the occupants from being injured in an accident, particularly in the event of a roll-over in the desert which is very rare. Plus there are seat belts for every passenger. We use 4x4 Land Cruisers for our safari. Also from the moment you are in our cars you are insured. All our cars and the passengers are covered under insurance.",
    MUSTDO:"MUST DO'S",
    MUSTDOData:"One must get a camera when going to a desert safari in Dubai as the views are breath-taking and awesome. Also one should wear comfortable clothes and avoid jewelry or expensive watch and cell phones as there is no signal at the camps. Do try the Arabic coffee at the camp and shake your belly with our belly dancer!",
    SANDSKI:"SAND SKI",
    SANDSKIData:"A very popular part of the desert safari. You get to ski from the highest dunes on a ski board, everyone can do it, as if you fall the soft sand is there to catch you. A thrilling experience and one that everyone should do a desert safari. We recommend you to book the red dune safari to enjoy sand-skiing the best.",
    // CAMELTREK:"CAMEL TREK",
    // CAMELTREKData:"Another popular activity in the desert is the camel trek. Enjoy the sunset while you are on the highest dune going towards the camp where you have drinks and dinner waiting for you.",
    price:"19",
    image:dhow1,
    timeAndDate:"7PM TO 11PM",
    totalGuest:"30"
},
{
    name:"Dubai Ferry Ride",
    desription:"Hop, aboard the new Dubai Ferry with routine that circle the city historical sites and striking coastline, it provides pleasant change of scenery. And with a luxurious interior you can rest assured your journey will be comfortable as it is memorable.The Dubai Ferry plies along the Dubai Marina, the Dubai Creek. The Ferry plies on several routes that go from one port to another so that the people on board can enjoy a good view of the attractions on the shorelines. There are Dubai Ferry stations at either end of Dubai. There’s one on the Dubai Marina, and in Al Ghubaiba. ",
    ofers1:"Pick up by 4x4 wheel Drive from any point in Dubai between 3.00 PM to 3.30 PM – timings are subject to change as per sunset time",
    ofers2:" Drive through the desert along Al Awir Road - Dune Bashing",
    ofers3:" 20-30 minutes Dune Driving",
    ofers4:" Sun Set Photography",
    ofers5:" Camel Rides",
    ofers6:" Belly Dancing (not during Ramadan)",
    ofers7:" Fire show and Tanura show",
    desr2:"There is no minimum people required for this package, even 1 person can do this. The best is if you have a group of 6 people in which you get a complete car for your group and don't have to share it with other guests. Please note as the desert safari is an adventure activity we do not recommend children below 3 years, pregnant women and older adults especially with back problems. But we can arrange private car that can take you directly to the camp so that you may enjoy other activities in the camp. We also have car seats for children.",
    SAFETY:"SAFETY",
    SAFETYData:"Our drivers are professional and licensed drivers and are trained in first aid. Our cars are fitted with roll cage to protect the occupants from being injured in an accident, particularly in the event of a roll-over in the desert which is very rare. Plus there are seat belts for every passenger. We use 4x4 Land Cruisers for our safari. Also from the moment you are in our cars you are insured. All our cars and the passengers are covered under insurance.",
    MUSTDO:"MUST DO'S",
    MUSTDOData:"One must get a camera when going to a desert safari in Dubai as the views are breath-taking and awesome. Also one should wear comfortable clothes and avoid jewelry or expensive watch and cell phones as there is no signal at the camps. Do try the Arabic coffee at the camp and shake your belly with our belly dancer!",
    SANDSKI:"SAND SKI",
    SANDSKIData:"A very popular part of the desert safari. You get to ski from the highest dunes on a ski board, everyone can do it, as if you fall the soft sand is there to catch you. A thrilling experience and one that everyone should do a desert safari. We recommend you to book the red dune safari to enjoy sand-skiing the best.",
    // CAMELTREK:"CAMEL TREK",
    // CAMELTREKData:"Another popular activity in the desert is the camel trek. Enjoy the sunset while you are on the highest dune going towards the camp where you have drinks and dinner waiting for you.",
    price:"39",
    image:dhow2,
    timeAndDate:"Up To Guests",
    totalGuest:"15"
},
{
    name:"Luxuary Yatch's",
    size1:"44 Ft luxury Yacht in Dubai ",
    desription:" Find yourself ensconced in luxury as we take you on an exciting cruise sailing along Dubai’s mesmerizing coastline. It’s an ideal escape from the noise and crowd of Dubai city as we take you on a calm ride on the waters of Dubai’s seas. Our yachts are lined with facilities that pamper you like royalty. The staff on board is always more than happy to welcome you on to the yacht as you embark on a wonderful ride. It’s an absolute joy cruising through the calm waters of Dubai’s seas as you take in the bright sunshine. Our 44 feet yachts are equipped with modern facilities, and you are left truly spoilt for choice. These yachts are ideal for a cozy get together with your near and dear ones with whom you can spend some quality time.",
    ofers1:"A professional crew thoroughly trained in luxurious hospitality management",
    ofers2:"A cruise on the Dubai Marina",
    ofers3:"Life jackets for your safety",
    ofers4:"Refreshments to keep your batteries charged",
    ofers5:"Safety equipment",
    ofers6:"Lifejackets",
    ofers7:"Drinking water",
    ofers8:"Towels",
    ofers9:"Insurance",
    ofers10:"You can get 4-star catering or any other additional services, at extra cost",
    ofers11:"Our latest Equipment help you get a catch in Fishing",
    ofers12:"You can try out some Snorkeling or Take a dip only before Sunset",
    price:"1300",
    desr2:"Hiring a luxury private yacht is not the only option available now! There is good news for couples, friends and small groups wanting to explore Dubai Sea without having to hire a private yacht, but enjoy all luxuries associated to it. Xclusive Yachts presents Xclusive Yacht Share Tours operating four times a day.",
    image:dhow3,
    timeAndDate:"Up To Guests",
    totalGuest:"11"
},
{
    name:"Dhow Marina Curise",
    desription:"This tour starts in the afternoon across the desert of Dubai with several stops for photography. During an exciting dune drive you arrive at the first destination for a beautiful sunset. We stop to watch the sunset and continue with Dune bashing to finally reach our campsite. Here you have the opportunity to do a camel ride, sand boarding and try out a henna design on hand or feet. After working up an appetite you get to enjoy a delicious barbecue dinner and shisha (the famous Arabic water pipe). You also get to enjoy our Fire show and Tanura show performance around the campfire by starlight.",
    ofers1:"Pick up by 4x4 wheel Drive from any point in Dubai between 3.00 PM to 3.30 PM – timings are subject to change as per sunset time",
    ofers2:" Drive through the desert along Al Awir Road - Dune Bashing",
    ofers3:" 20-30 minutes Dune Driving",
    ofers4:" Sun Set Photography",
    ofers5:" Camel Rides",
    ofers6:" Belly Dancing (not during Ramadan)",
    ofers7:" Fire show and Tanura show",
    desr2:"There is no minimum people required for this package, even 1 person can do this. The best is if you have a group of 6 people in which you get a complete car for your group and don't have to share it with other guests. Please note as the desert safari is an adventure activity we do not recommend children below 3 years, pregnant women and older adults especially with back problems. But we can arrange private car that can take you directly to the camp so that you may enjoy other activities in the camp. We also have car seats for children.",
    SAFETY:"SAFETY",
    SAFETYData:"Our drivers are professional and licensed drivers and are trained in first aid. Our cars are fitted with roll cage to protect the occupants from being injured in an accident, particularly in the event of a roll-over in the desert which is very rare. Plus there are seat belts for every passenger. We use 4x4 Land Cruisers for our safari. Also from the moment you are in our cars you are insured. All our cars and the passengers are covered under insurance.",
    MUSTDO:"MUST DO'S",
    MUSTDOData:"One must get a camera when going to a desert safari in Dubai as the views are breath-taking and awesome. Also one should wear comfortable clothes and avoid jewelry or expensive watch and cell phones as there is no signal at the camps. Do try the Arabic coffee at the camp and shake your belly with our belly dancer!",
    SANDSKI:"SAND SKI",
    SANDSKIData:"A very popular part of the desert safari. You get to ski from the highest dunes on a ski board, everyone can do it, as if you fall the soft sand is there to catch you. A thrilling experience and one that everyone should do a desert safari. We recommend you to book the red dune safari to enjoy sand-skiing the best.",
    CAMELTREK:"CAMEL TREK",
    CAMELTREKData:"Another popular activity in the desert is the camel trek. Enjoy the sunset while you are on the highest dune going towards the camp where you have drinks and dinner waiting for you.",
    price:"129",
    image:dhow4,
    timeAndDate:"7PM TO 11PM",
    totalGuest:"11"
},

 
]
