
import yellow from "../assets/images/yellow.jpg"
import blon from "../assets/images/blon.jfif"
import bua from "../assets/images/bua.jfif"
import jet from "../assets/images/jet.jfif"
export const ticketAdvanureArray=[
    {
    name:"Yellow Boat",
    desription:"This tour starts in the afternoon across the desert of Dubai with several stops for photography. During an exciting dune drive you arrive at the first destination for a beautiful sunset. We stop to watch the sunset and continue with Dune bashing to finally reach our campsite. Here you have the opportunity to do a camel ride, sand boarding and try out a henna design on hand or feet. After working up an appetite you get to enjoy a delicious barbecue dinner and shisha (the famous Arabic water pipe). You also get to enjoy our Fire show and Tanura show performance around the campfire by starlight.",
    //ofers1:"Pick up by 4x4 wheel Drive from any point in Dubai between 3.00 PM to 3.30 PM – timings are subject to change as per sunset time",
    ofers2:" Drive through the desert along Al Awir Road - Dune Bashing",
    ofers3:" 20-30 minutes Dune Driving",
    ofers4:" Sun Set Photography",
    ofers5:" Camel Rides",
    ofers6:" Belly Dancing (not during Ramadan)",
    ofers7:" Fire show and Tanura show",
    desr2:"There is no minimum people required for this package, even 1 person can do this. The best is if you have a group of 6 people in which you get a complete car for your group and don't have to share it with other guests. Please note as the desert safari is an adventure activity we do not recommend children below 3 years, pregnant women and older adults especially with back problems. But we can arrange private car that can take you directly to the camp so that you may enjoy other activities in the camp. We also have car seats for children.",
    SAFETY:"SAFETY",
    SAFETYData:"Our drivers are professional and licensed drivers and are trained in first aid. Our cars are fitted with roll cage to protect the occupants from being injured in an accident, particularly in the event of a roll-over in the desert which is very rare. Plus there are seat belts for every passenger. We use 4x4 Land Cruisers for our safari. Also from the moment you are in our cars you are insured. All our cars and the passengers are covered under insurance.",
    MUSTDO:"MUST DO'S",
    MUSTDOData:"One must get a camera when going to a desert safari in Dubai as the views are breath-taking and awesome. Also one should wear comfortable clothes and avoid jewelry or expensive watch and cell phones as there is no signal at the camps. Do try the Arabic coffee at the camp and shake your belly with our belly dancer!",
    SANDSKI:"SAND SKI",
    SANDSKIData:"A very popular part of the desert safari. You get to ski from the highest dunes on a ski board, everyone can do it, as if you fall the soft sand is there to catch you. A thrilling experience and one that everyone should do a desert safari. We recommend you to book the red dune safari to enjoy sand-skiing the best.",
    CAMELTREK:"CAMEL TREK",
    CAMELTREKData:"Another popular activity in the desert is the camel trek. Enjoy the sunset while you are on the highest dune going towards the camp where you have drinks and dinner waiting for you.",
    price:"200",
    image:yellow,
    timeAndDate:"1PM - 3PM, 20th Apr (3 Hours)",
    totalGuest:"45 minutes (Approx)"
},
{
    name:"Ballon Ride",
    desription:"This tour starts in the afternoon across the desert of Dubai with several stops for photography. During an exciting dune drive you arrive at the first destination for a beautiful sunset. We stop to watch the sunset and continue with Dune bashing to finally reach our campsite. Here you have the opportunity to do a camel ride, sand boarding and try out a henna design on hand or feet. After working up an appetite you get to enjoy a delicious barbecue dinner and shisha (the famous Arabic water pipe). You also get to enjoy our Fire show and Tanura show performance around the campfire by starlight.",
    //ofers1:"Pick up by 4x4 wheel Drive from any point in Dubai between 3.00 PM to 3.30 PM – timings are subject to change as per sunset time",
    ofers2:" Drive through the desert along Al Awir Road - Dune Bashing",
    ofers3:" 20-30 minutes Dune Driving",
    ofers4:" Sun Set Photography",
    ofers5:" Camel Rides",
    ofers6:" Belly Dancing (not during Ramadan)",
    ofers7:" Fire show and Tanura show",
    desr2:"There is no minimum people required for this package, even 1 person can do this. The best is if you have a group of 6 people in which you get a complete car for your group and don't have to share it with other guests. Please note as the desert safari is an adventure activity we do not recommend children below 3 years, pregnant women and older adults especially with back problems. But we can arrange private car that can take you directly to the camp so that you may enjoy other activities in the camp. We also have car seats for children.",
    SAFETY:"SAFETY",
    SAFETYData:"Our drivers are professional and licensed drivers and are trained in first aid. Our cars are fitted with roll cage to protect the occupants from being injured in an accident, particularly in the event of a roll-over in the desert which is very rare. Plus there are seat belts for every passenger. We use 4x4 Land Cruisers for our safari. Also from the moment you are in our cars you are insured. All our cars and the passengers are covered under insurance.",
    MUSTDO:"MUST DO'S",
    MUSTDOData:"One must get a camera when going to a desert safari in Dubai as the views are breath-taking and awesome. Also one should wear comfortable clothes and avoid jewelry or expensive watch and cell phones as there is no signal at the camps. Do try the Arabic coffee at the camp and shake your belly with our belly dancer!",
    SANDSKI:"SAND SKI",
    SANDSKIData:"A very popular part of the desert safari. You get to ski from the highest dunes on a ski board, everyone can do it, as if you fall the soft sand is there to catch you. A thrilling experience and one that everyone should do a desert safari. We recommend you to book the red dune safari to enjoy sand-skiing the best.",
    CAMELTREK:"CAMEL TREK",
    CAMELTREKData:"Another popular activity in the desert is the camel trek. Enjoy the sunset while you are on the highest dune going towards the camp where you have drinks and dinner waiting for you.",
    price:"1500",
    image:blon,
    timeAndDate:"12PM - 3PM, 20th Apr (3 Hours)",
    totalGuest:"4 To 5 Hours Tour"
},
{
    name:"Big Bus Tour",
    desription:"This tour starts in the afternoon across the desert of Dubai with several stops for photography. During an exciting dune drive you arrive at the first destination for a beautiful sunset. We stop to watch the sunset and continue with Dune bashing to finally reach our campsite. Here you have the opportunity to do a camel ride, sand boarding and try out a henna design on hand or feet. After working up an appetite you get to enjoy a delicious barbecue dinner and shisha (the famous Arabic water pipe). You also get to enjoy our Fire show and Tanura show performance around the campfire by starlight.",
    //ofers1:"Pick up by 4x4 wheel Drive from any point in Dubai between 3.00 PM to 3.30 PM – timings are subject to change as per sunset time",
    ofers2:" Drive through the desert along Al Awir Road - Dune Bashing",
    ofers3:" 20-30 minutes Dune Driving",
    ofers4:" Sun Set Photography",
    ofers5:" Camel Rides",
    ofers6:" Belly Dancing (not during Ramadan)",
    ofers7:" Fire show and Tanura show",
    desr2:"There is no minimum people required for this package, even 1 person can do this. The best is if you have a group of 6 people in which you get a complete car for your group and don't have to share it with other guests. Please note as the desert safari is an adventure activity we do not recommend children below 3 years, pregnant women and older adults especially with back problems. But we can arrange private car that can take you directly to the camp so that you may enjoy other activities in the camp. We also have car seats for children.",
    SAFETY:"SAFETY",
    SAFETYData:"Our drivers are professional and licensed drivers and are trained in first aid. Our cars are fitted with roll cage to protect the occupants from being injured in an accident, particularly in the event of a roll-over in the desert which is very rare. Plus there are seat belts for every passenger. We use 4x4 Land Cruisers for our safari. Also from the moment you are in our cars you are insured. All our cars and the passengers are covered under insurance.",
    MUSTDO:"MUST DO'S",
    MUSTDOData:"One must get a camera when going to a desert safari in Dubai as the views are breath-taking and awesome. Also one should wear comfortable clothes and avoid jewelry or expensive watch and cell phones as there is no signal at the camps. Do try the Arabic coffee at the camp and shake your belly with our belly dancer!",
    SANDSKI:"SAND SKI",
    SANDSKIData:"A very popular part of the desert safari. You get to ski from the highest dunes on a ski board, everyone can do it, as if you fall the soft sand is there to catch you. A thrilling experience and one that everyone should do a desert safari. We recommend you to book the red dune safari to enjoy sand-skiing the best.",
    CAMELTREK:"CAMEL TREK",
    CAMELTREKData:"Another popular activity in the desert is the camel trek. Enjoy the sunset while you are on the highest dune going towards the camp where you have drinks and dinner waiting for you.",
    price:"200",
    image:bua,
    timeAndDate:"3PM - 3PM, 20th Apr (3 Hours)",
    totalGuest:"Duration : 4 Hours"
},
{
    name:"Burj Al Arab Jet Ski Tour",
    desription:"This tour starts in the afternoon across the desert of Dubai with several stops for photography. During an exciting dune drive you arrive at the first destination for a beautiful sunset. We stop to watch the sunset and continue with Dune bashing to finally reach our campsite. Here you have the opportunity to do a camel ride, sand boarding and try out a henna design on hand or feet. After working up an appetite you get to enjoy a delicious barbecue dinner and shisha (the famous Arabic water pipe). You also get to enjoy our Fire show and Tanura show performance around the campfire by starlight.",
    //ofers1:"Pick up by 4x4 wheel Drive from any point in Dubai between 3.00 PM to 3.30 PM – timings are subject to change as per sunset time",
    ofers2:" Drive through the desert along Al Awir Road - Dune Bashing",
    ofers3:" 20-30 minutes Dune Driving",
    ofers4:" Sun Set Photography",
    ofers5:" Camel Rides",
    ofers6:" Belly Dancing (not during Ramadan)",
    ofers7:" Fire show and Tanura show",
    desr2:"There is no minimum people required for this package, even 1 person can do this. The best is if you have a group of 6 people in which you get a complete car for your group and don't have to share it with other guests. Please note as the desert safari is an adventure activity we do not recommend children below 3 years, pregnant women and older adults especially with back problems. But we can arrange private car that can take you directly to the camp so that you may enjoy other activities in the camp. We also have car seats for children.",
    SAFETY:"SAFETY",
    SAFETYData:"Our drivers are professional and licensed drivers and are trained in first aid. Our cars are fitted with roll cage to protect the occupants from being injured in an accident, particularly in the event of a roll-over in the desert which is very rare. Plus there are seat belts for every passenger. We use 4x4 Land Cruisers for our safari. Also from the moment you are in our cars you are insured. All our cars and the passengers are covered under insurance.",
    MUSTDO:"MUST DO'S",
    MUSTDOData:"One must get a camera when going to a desert safari in Dubai as the views are breath-taking and awesome. Also one should wear comfortable clothes and avoid jewelry or expensive watch and cell phones as there is no signal at the camps. Do try the Arabic coffee at the camp and shake your belly with our belly dancer!",
    SANDSKI:"SAND SKI",
    SANDSKIData:"A very popular part of the desert safari. You get to ski from the highest dunes on a ski board, everyone can do it, as if you fall the soft sand is there to catch you. A thrilling experience and one that everyone should do a desert safari. We recommend you to book the red dune safari to enjoy sand-skiing the best.",
    CAMELTREK:"CAMEL TREK",
    CAMELTREKData:"Another popular activity in the desert is the camel trek. Enjoy the sunset while you are on the highest dune going towards the camp where you have drinks and dinner waiting for you.",
    price:"",
    image:jet,
    timeAndDate:"3PM - 3PM, 20th Apr (3 Hours)",
    totalGuest:"Duration : 30 Minutes"
},
// {
//     name:"Dubai Fram",
//     desription:"This tour starts in the afternoon across the desert of Dubai with several stops for photography. During an exciting dune drive you arrive at the first destination for a beautiful sunset. We stop to watch the sunset and continue with Dune bashing to finally reach our campsite. Here you have the opportunity to do a camel ride, sand boarding and try out a henna design on hand or feet. After working up an appetite you get to enjoy a delicious barbecue dinner and shisha (the famous Arabic water pipe). You also get to enjoy our Fire show and Tanura show performance around the campfire by starlight.",
//     ofers1:"Pick up by 4x4 wheel Drive from any point in Dubai between 3.00 PM to 3.30 PM – timings are subject to change as per sunset time",
//     ofers2:" Drive through the desert along Al Awir Road - Dune Bashing",
//     ofers3:" 20-30 minutes Dune Driving",
//     ofers4:" Sun Set Photography",
//     ofers5:" Camel Rides",
//     ofers6:" Belly Dancing (not during Ramadan)",
//     ofers7:" Fire show and Tanura show",
//     desr2:"There is no minimum people required for this package, even 1 person can do this. The best is if you have a group of 6 people in which you get a complete car for your group and don't have to share it with other guests. Please note as the desert safari is an adventure activity we do not recommend children below 3 years, pregnant women and older adults especially with back problems. But we can arrange private car that can take you directly to the camp so that you may enjoy other activities in the camp. We also have car seats for children.",
//     SAFETY:"SAFETY",
//     SAFETYData:"Our drivers are professional and licensed drivers and are trained in first aid. Our cars are fitted with roll cage to protect the occupants from being injured in an accident, particularly in the event of a roll-over in the desert which is very rare. Plus there are seat belts for every passenger. We use 4x4 Land Cruisers for our safari. Also from the moment you are in our cars you are insured. All our cars and the passengers are covered under insurance.",
//     MUSTDO:"MUST DO'S",
//     MUSTDOData:"One must get a camera when going to a desert safari in Dubai as the views are breath-taking and awesome. Also one should wear comfortable clothes and avoid jewelry or expensive watch and cell phones as there is no signal at the camps. Do try the Arabic coffee at the camp and shake your belly with our belly dancer!",
//     SANDSKI:"SAND SKI",
//     SANDSKIData:"A very popular part of the desert safari. You get to ski from the highest dunes on a ski board, everyone can do it, as if you fall the soft sand is there to catch you. A thrilling experience and one that everyone should do a desert safari. We recommend you to book the red dune safari to enjoy sand-skiing the best.",
//     CAMELTREK:"CAMEL TREK",
//     CAMELTREKData:"Another popular activity in the desert is the camel trek. Enjoy the sunset while you are on the highest dune going towards the camp where you have drinks and dinner waiting for you.",
//     price:"$501",
//     image:cardImage,
//     timeAndDate:"3PM - 3PM, 20th Apr (3 Hours)",
//     totalGuest:"11"
// },

 
]
